[project]
name = "lab1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=1.97.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
